name: litter_star
description: An interactive educational app for kids to learn Vietnamese and watch safe content.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Futura
      fonts:
        - asset: fonts/SFUFuturaRegular.TTF
        - asset: fonts/SFUFuturaOblique.TTF
          style: italic
        - asset: fonts/SFUFuturaHeavy.TTF
          weight: 500
        - asset: fonts/SFUFuturaHeavyOblique.TTF
          weight: 500
          style: italic
        - asset: fonts/SFUFuturaBold.TTF
          weight: 700
        - asset: fonts/SFUFuturaBoldOblique.TTF
          weight: 700
          style: italic
        - asset: fonts/SFUFuturaExtraBold.TTF
          weight: 900
        - asset: fonts/SFUFuturaExtraBoldOblique.TTF
          weight: 900
          style: italic
