name: litter_star
description: An interactive educational app for kids to learn Vietnamese and watch safe content.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.0
  percent_indicator: ^3.4.0
  url_launcher: ^6.0.20
  flame_audio: ^1.0.0
  flutter_switch: ^0.3.2
  video_player: ^2.2.19
  shared_preferences: ^2.0.13
  permission_handler: ^9.2.0
  flutter_widget_from_html_core: ^0.8.5+1
  fwfh_webview: ^0.6.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icons/
  - assets/audio/
  - assets/images/alphabet/
  - assets/fonts/
  fonts:
  - family: HP
    fonts:
    - asset: assets/fonts/HP001_4_hang_bold.ttf
  

flutter_app_name:
  name: "Little Star"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"